sudo: required
language: python
python:
  - 2.7
install:
  - pip install flake8 yapf

services:
  - docker
  - git

git:
  depth: 1

script:
  - ./check_code || travis_terminate 1;
  - ./travis_build.sh || travis_terminate 1;
